-- Script para crear las bases de datos BONUS_TRACK y LIBRERÍA
-- y sus respectivas tablas

-- Crear base de datos BONUS_TRACK
CREATE DATABASE IF NOT EXISTS BONUS_TRACK;
USE BONUS_TRACK;

-- Tabla AUTORES
CREATE TABLE AUTORES (
    ID_AUTOR INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    NACIONALIDAD VARCHAR(50),
    FECHA_NACIMIENTO DATE
);

-- Tabla EMPLEADOS
CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    PUESTO VARCHAR(50),
    FECHA_INGRESO DATE,
    SALARIO DECIMAL(10,2)
);

-- Crear base de datos LIBRERÍA
CREATE DATABASE IF NOT EXISTS LIBRERIA;
USE LIBRERIA;

-- Tabla LIBROS
CREATE TABLE LIBROS (
    ID_LIBRO INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(100) NOT NULL,
    AUTOR VARCHAR(100),
    EDITORIAL VARCHAR(50),
    PRECIO DECIMAL(10,2),
    STOCK INT,
    FECHA_PUBLICACION DATE
);
